# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2ZmOGIzZGI1MmQ1MmUzMzFkZWNhNGVkNTg4YzA1OGQxY2MwODU0ZDJkOWNhNWYxMTg5ODQ2ZjE3MGVmNjgzYzMxYTcxMDUzZjY4M2IxM2JlOWQ5NDhlYjE5YzdkZjk0NTdjNjZlYWM2NzNhMWYzODg2ZTIyYjc0NWY4YzVjNWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
